#! /bin/bash
# List available commands


printCommand() {
    echo -e $CYAN $1 $RESET $2
}

listCommands() {
    echo -e $YELLOW 'Commands'
    printCommand 'start' '| Start and instance of the server (this will also kill the current server if there is one and check for updates)'
    printCommand 'stop ' '| Kill the current running instance of the server'
}

