#! /bin/bash
# Start the server

startServer() {
    # Run the server startup script
    cd $SERVER_FILES
    $START

    # Check that the server has started
    updatePid $!
    
    if [[ $(ps -aux | grep $GREP_PID) ]]
    then
        success 'Server started! PID:'$RUNNING_PID
        updatePid $RUNNING_PID
    else
        error 'Failed to start server'
        updatePid ''
        exit 1
    fi
}
